# Dependabot configuration:
# https://docs.github.com/en/code-security/how-tos/secure-your-supply-chain/secure-your-dependencies/configure-version-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
