# Unsupported as of 2026-06-28, causes issues with Dependabot & Renovate
#configDependencies:
#  '@pnpm/plugin-better-defaults': 0.3.0
#  '@pnpm/plugin-trusted-deps': 0.2.2

minimumReleaseAge: 1440
minimumReleaseAgeStrict: true

packages:
  - 'apps/*'
  - 'packages/**'
