$schema: ../cache/schemas/tasks.json

inheritedBy:
  tag: "vitest"

fileGroups:
  vitest:
    - "src/**/*"
    - "vitest.config.*"
  sources: []
  tests:
    - "tests/**/*"

tasks:
  test:
    description: "Run unit tests"
    command:
      - "vitest run --passWithNoTests"
    inputs:
      - "@group(vitest)"
      - "@group(sources)"
      - "@group(tests)"

  test-cov:
    extends: "test"
    description: "Run with code coverage"
    args: "--coverage"
    outputs:
      - "coverage/**/*"

  test-watch:
    description: "Watch for test changes"
    command: "vitest watch"
    preset: "server"
