$schema: ../cache/schemas/tasks.json

inheritedBy:
  tag: 'vite'

fileGroups:
  vite:
    - 'public/**/*'
    - 'src/**/*'
    - 'vite.config.*'
  sources: []

tasks:
  build:
    description: 'Build the application'
    command: 'vite build'
    inputs:
      - '@group(vite)'
      - '@group(sources)'
    outputs:
      - 'dist/**/*'

  dev:
    description: 'Run the development server'
    command: 'vite dev'
    preset: server

  preview:
    description: 'Preview the built application'
    command: 'vite preview'
    deps:
      - '~:build'
    preset: server
