name: CI (pull request)

on:
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ci-pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  moon-ci:
    permissions:
      contents: read
      checks: write
      pull-requests: write
    uses: ./.github/workflows/_reusable-moon-ci.yml
    secrets:
      buildfetch-token: ${{ secrets.BUILDFETCH_TOKEN_READONLY }}

  docker-build:
    needs: moon-ci
    uses: ./.github/workflows/_reusable-docker-build.yml
    with:
      attestations: false
    secrets:
      buildfetch-token: ${{ secrets.BUILDFETCH_TOKEN_READONLY }}
    permissions:
      contents: read
      packages: write
      id-token: write
