name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          filter: blob:none

      - name: Set up toolchain
        uses: moonrepo/setup-toolchain@261c62cb5b0f580c7be7c8cd0f023a2e96756095 # v0.6.4
        with:
          auto-install: true
          proto-version: "0.61.2" # renovate: datasource=github-releases depName=moonrepo/proto extractVersion=^v(?<version>.*)$

      - name: Run Moon CI
        run: moon ci

      - uses: moonrepo/run-report-action@bbe7e99bf2aca819ec660ec01fc59d84bdd492d6 # v1.10.0
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
